language: python
python:
  - "3.6.0"
install:
  - pip install -r requirements.txt
  - pip install  pytest
  - pip install  pytest-cov
script: 
  - pytest --cov=api/
  - coverage
  - coveralls
  - coveralls
after-success:
  coveralls