language: python
python:
- "3.6.0"
install:
- pip install pytest-cov
- pip install coveralls
- pip install -r requirements.txt
script: 
- pytest --cov=.
- coverage
- coveralls
after-success:
- coveralls