language: python
python:
  - "3.6.0"
install:
  - pip install -r requirements.txt
  - pip install -r pytest
script: 
  - pytest --cov=api/
  - coverage
  - coveralls
  - coveralls
after-success:
  coveralls